/Users/nikki/nublabs/nub.datalogger/hardware/temperature_sensor_Terciopelo/applet/temperature_sensor_Terciopelo.cpp File Reference
#include `name.h`
#include `globals.h`
#include `communications_definitions.h`
#include <stdio.h>
#include `WProgram.h`
Defines
#define XBEE_SLEEP 2
#define SAMPLE_BUTTON 3
#define LED 4
#define SENSOR1_TOP 0
#define SENSOR1_BOTTOM 1
#define SENSOR2_TOP 2
#define SENSOR2_BOTTOM 3
Functions
void setup ()
void loop ()
void sample ()
int getByte (int timeout)
int getMessage (int timeout)
void sendData ()
this function takes care of putting together a message string, calculating a checksum, sending it out to the computer and making sure the computer got it ok
unsigned char getChecksum ()
this computes a checksum of the global string 'message'
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
void discover ()
This function tells the computer of the datalogger's existence.
void waitForSampleInterval ()
this function waits for the time specified by the global variables 'hours,' 'minutes,' and 'seconds' It should ideally put the arduino in a power saving mode
void initializeSensor ()
this function configures all the digital communication pins as input or output pins
void xbeeSleep ()
void xbeeWake ()
void getTemperatures ()
void getRawData ()
this just grabs the raw values off the analog to digital converter
void convertToResistance ()
this function converts the raw ADC values from the thermistor into resistances of the thermistor
void convertToTemperature ()
int main (void)
Variables
float R0 = 10000.0
float B = 3950.0
float T0 = 298
float RBOTTOM = 1000.0
Define Documentation
#define LED 4
Definition at line 348 of file temperature_sensor_Terciopelo.cpp.
#define SAMPLE_BUTTON 3
Definition at line 347 of file temperature_sensor_Terciopelo.cpp.
#define SENSOR1_BOTTOM 1
Definition at line 351 of file temperature_sensor_Terciopelo.cpp.
#define SENSOR1_TOP 0
Definition at line 350 of file temperature_sensor_Terciopelo.cpp.
#define SENSOR2_BOTTOM 3
Definition at line 353 of file temperature_sensor_Terciopelo.cpp.
#define SENSOR2_TOP 2
Definition at line 352 of file temperature_sensor_Terciopelo.cpp.
#define XBEE_SLEEP 2
these are the pin definitions for the v2 board
function atmega pin arduino pin
Serial RX PD0 0 //serial lines that go out to the xbee module Serial TX PD1 1 Xbee_sleep PD2 2 //a pin that, when asserted, puts the xbee radio into a low power sleep mode Sample_button PD3 3 //an optional button that forces the sensor to take and send out a measurement LED PD4 4 //an LED on board that you can use for all kinds of stuff
sensor1_top PC0 (analog) 0 sensor1_bottom PC1 (analog) 1 sensor2_top PC2 (analog) 2 sensor2_bottom PC3 (analog) 3
Definition at line 346 of file temperature_sensor_Terciopelo.cpp.
Function Documentation
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
Definition at line 15 of file nublogger.h.
References buffer, CHECKSUM, CHECKSUM_ERROR_GIVING_UP, CHECKSUM_ERROR_PLEASE_RESEND, CONFIGURATION_MESSAGE_LENGTH, configured, getMessage(), HOUR_HIGH, HOUR_LOW, hours, index, LISTENING, MALFORMED_MESSAGE_ERROR_GIVING_UP, MALFORMED_MESSAGE_ERROR_PLEASE_RESEND, MESSAGE_START, MINUTE_HIGH, MINUTE_LOW, minutes, NUM_TRIES, SECOND_HIGH, SECOND_LOW, seconds, start, and TIMEOUT_ERROR.
Referenced by discover(), and sendData().
16 { 
17 }
void convertToResistance ()
this function converts the raw ADC values from the thermistor into resistances of the thermistor
Definition at line 408 of file temperature_sensor_Terciopelo.cpp.
References RBOTTOM, sensor1_bottom, sensor1_resistance, and sensor1_top.
Referenced by getTemperatures(), and sample().
409 {
410   sensor1_resistance = ((float)sensor1_top/(float)sensor1_bottom - 1)*RBOTTOM; // Voltages converted to resistances
411   /* uncomment if I enable two sensing elements
412    sensor2_resistance = ((float)sensor2_top/(float)sensor2_bottom - 1)*RBOTTOM; // Voltages converted to resistances*/
413    int a=(int) sensor1_resistance;
414    Serial.println("woohoo!");
415 //  Serial.println(a,DEC);
416 }
void convertToTemperature ()
Definition at line 419 of file temperature_sensor_Terciopelo.cpp.
References B, R0, sensor1_resistance, sensor1_temperature, and T0.
Referenced by getTemperatures(), and sample().
420 {
421   sensor1_temperature = float(B/log(sensor1_resistance/(R0*exp(-1.0*B/T0))) - 273.0); // Temperature in degrees Celsius
422   /* uncomment if I enable two sensing elements
423    sensor2_temperature = float(B/log(sensor2_resistance/(R0*exp(-1.0*B/T0))) - 273.0); // Temperature in degrees Celsius   */
424 }
void discover ()
This function tells the computer of the datalogger's existence.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
Definition at line 27 of file nublogger.h.
References ACKNOWLEDGE, ACKNOWLEDGE_AND_CONFIGURE, configure(), DISCOVER_ME, discovered, getByte(), MESSAGE_END, MESSAGE_START, name, TIMEOUT_ERROR, and TRUE.
Referenced by setup().
28 { 
29   unsigned char checksum=0;
30   int i=0;
31   Serial.print(MESSAGE_START, BYTE);
32   Serial.print(DISCOVER_ME,BYTE);
33   Serial.print(name);
34   while(name[i]!=0)
35   {
36     checksum+=name[i];
37     i++;
38   }
39   checksum+=DISCOVER_ME;
40   Serial.print(checksum,BYTE);
41   Serial.print(MESSAGE_END,BYTE);
42 
43   int receivedByte=getByte(100);     //looks for a byte on the serial port with a 100ms timeout
44   if(receivedByte==ACKNOWLEDGE)
45     discovered=TRUE;
46   if(receivedByte==ACKNOWLEDGE_AND_CONFIGURE)
47     {
48       discovered=TRUE;
49       configure();
50     }
51   
52 }
int getByte (int timeout)
Definition at line 4 of file communications.h.
Referenced by discover(), and sendData().
5 {
6   int currentTime=millis();
7   int maxTime=currentTime+timeout;
8   while((Serial.available()==0)&&(millis()<(maxTime)))
9     {}
10   if((millis()>maxTime)||(Serial.available()==0))
11     return -1;
12   else
13     return Serial.read();
14 }
unsigned char getChecksum ()
this computes a checksum of the global string 'message'
Definition at line 184 of file temperature_sensor_Terciopelo.cpp.
References message.
Referenced by sendData().
185 {
186   char i=0;
187   unsigned char checksum=0;
188   while(message[i]!=0)
189   {
190     checksum+=message[i];
191     i++;
192   }
193   return checksum;
194 }
int getMessage (int timeout)
Definition at line 127 of file temperature_sensor_Terciopelo.cpp.
References buffer, index, MESSAGE_END, and start.
Referenced by configure().
128 {
129   int completeMessage=-1;   //a flag that lets us know if we got a full message
130   start=index;              //drop whatever other data is in our buffer--it'll probably just confuse the functions if we don't
131   int currentTime=millis();
132   int maxTime=currentTime+timeout;  
133   while((millis()<(maxTime))&&(buffer[index]!=MESSAGE_END))
134   {
135     if(Serial.available()>0)
136     {
137       buffer[index]=Serial.read();
138       if(buffer[index]==MESSAGE_END)   //we got a complete message
139         completeMessage=1;
140       index++;
141     }
142   }
143   if(completeMessage==-1)    //we never got a complete message
144     start=index;    //skip past whatever we got from the buffer
145 
146   return completeMessage;
147 }
void getRawData ()
this just grabs the raw values off the analog to digital converter
Definition at line 397 of file temperature_sensor_Terciopelo.cpp.
References sensor1_bottom, and sensor1_top.
Referenced by getTemperatures(), and sample().
398 {
399   sensor1_top=analogRead(0);
400   sensor1_bottom=analogRead(1);
401 
402   /*  uncomment if I enable 2-sensing elements per sensor
403    sensor2_top=analogRead(2);
404    sensor2_bottom=analogRead(3);*/
405 }
void getTemperatures ()
Definition at line 389 of file temperature_sensor_Terciopelo.cpp.
References convertToResistance(), convertToTemperature(), and getRawData().
390 {
391   getRawData();
392   convertToResistance();
393   convertToTemperature();
394 }
void initializeSensor ()
this function configures all the digital communication pins as input or output pins
If you adapt this code to work with another sensor or board, you should replace the code in initializeSensor() to initialize all your relevant pins
If you adapt this code to work with another sensor or board, you should replace the code in initializeSensor() to initialize all your relevant pins
If you adapt this code to work with another sensor or board, you should replace the code in initializeSensor() to initialize all your relevant pins
If you adapt this code to work with another sensor or board, you should replace the code in initializeSensor() to initialize all your relevant pins
Definition at line 35 of file temperature_sensor_board_v2.h.
References LED, SAMPLE_BUTTON, XBEE_SLEEP, and xbeeWake().
Referenced by setup().
36  {
37    pinMode(XBEE_SLEEP,OUTPUT);
38    pinMode(SAMPLE_BUTTON,INPUT);
39    pinMode(LED,OUTPUT);
40  }
void loop ()
Definition at line 97 of file temperature_sensor_Terciopelo.cpp.
References sample(), and waitForSampleInterval().
Referenced by main().
98 {
99   waitForSampleInterval();
100   sample();
101 }
int main (void)
Definition at line 427 of file temperature_sensor_Terciopelo.cpp.
References loop(), and setup().
428 {
429         init();
430 
431         setup();
432     
433         for (;;)
434                 loop();
435         
436         return 0;
437 }
void sample ()
Definition at line 103 of file temperature_sensor_Terciopelo.cpp.
References convertToResistance(), convertToTemperature(), getRawData(), sampleNumber, and sendData().
Referenced by loop().
104 {
105   getRawData();
106   convertToResistance();
107   convertToTemperature();
108   sendData();
109   sampleNumber++;
110 }
void sendData ()
this function takes care of putting together a message string, calculating a checksum, sending it out to the computer and making sure the computer got it ok
Definition at line 151 of file temperature_sensor_Terciopelo.cpp.
References ACKNOWLEDGE, ACKNOWLEDGE_AND_CONFIGURE, configure(), FALSE, getByte(), getChecksum(), message, MESSAGE_END, MESSAGE_START, NUM_TRIES, sampleNumber, sensor1_temperature, and TRUE.
Referenced by sample().
152 {
153   char tries=0;
154   char success=FALSE;
155   int sensor1_temperature_decimals=(sensor1_temperature-(int)sensor1_temperature)*100;    //sprintf doesn't work for floats, so this hack gets 2 sigfigs
156   int response=0;
157  // sprintf(message,"%d", sampleNumber);
158   sprintf(message, " %d thermistor 1 = %d.%d degrees C", sampleNumber, (int)sensor1_temperature, sensor1_temperature_decimals);
159 //sprintf(message,"%d %d %d", (int) sensor1_temperature, (int) sensor1_resistance, sensor1_temperature_decimals);
160   unsigned char checksum=getChecksum();
161   while((success==FALSE)&&(tries<NUM_TRIES))
162   {
163     Serial.print(MESSAGE_START,BYTE);
164     Serial.print(message);
165     Serial.print(checksum);
166     Serial.print(MESSAGE_END,BYTE);
167     response=getByte(50);   //look for the computer's response
168 
169     if(response==ACKNOWLEDGE)   //the computer got the data.  It's happy, we're happy, we're done!
170       success=TRUE;
171 
172     else if(response==ACKNOWLEDGE_AND_CONFIGURE)  //the computer can ask to upload a new configuration at any sample
173     {
174       success=TRUE;
175       configure();
176     }
177     else         //if there was a timeout or a checksum mismatch, then re-try
178     tries++;
179   }
180 
181 }
void setup ()
nublogger temperature sensor Terciopelo(+)
Alex Hornstein 11.19.08 alex@nublabs.com datalogger.nublabs.com
(+)In keeping with the arduino nomenclature, we are naming all our code revisions with Spanish names of venemous snakes. The Terciopelo, or fer-de-lance is a pit viper common in central and northwestern south america. It has a powerful venom that, left untreated, can cause necrosis, brain hemorrhaging, renal failure and death. It's also capable of spraying venom through its fangs for up to 6 feet. Cool, huh? This is a sensor for nublab's datalogging system. The datalogger is a two-part system: There is a USB dongle that plugs into a computer that allows the computer to talk to a wireless Zigbee network, and then there are battery-powered sensors that sense data about the environemnt. The sensors collect data and convert it into human-readable units, and then send the data as plaintext over the wireless network to the computer, where it is stored and logged. Any sensor that will work with this system must implement the discover(), configure() and sample() functions, as well as be identifiable by a unique name
The discover() function is a short communication sequence when the sensor is first turned on where it broadcasts its name over the network and ensures that the computer recognizes it and is ready to configure it and log its data. The sensor also sends the units of whatever value it will be reporting.
the configure() function is triggered by a flag sent by the computer that indicates that the computer would like to change the datalogger's sample rate. configure() is another communication sequence in which the computer sends a sample interval in hours, minutes and seconds to the datalogger. By default, the datalogger samples every second.
the sample() function is called by the sensor every sample interval. sample() reads a value from whatever sensing element (Thermistor, current sensor, light sensor, etc) the particular sensor uses, converts it to physical units (degrees celsius, amps, lux, etc) and sends out a string over the wireless network with the sensor's unique name and its sensed values.
the name: each sensor should have a unique name burnt into its eeprom that makes it uniquely identifiable in the network. Nublabs is using a list of north and south american baby names which is available at datalogger.nublabs.com This particular sensor is a temperature sensor using an NTC thermistor. The thermistor is a resistive element. We sense it using two resistor dividers--one resistor, R1 which connects from Vcc to the thermistor, and another resistor that connects from the other end of the thermistor to ground. We measure the voltage at both ends of the thermistor using separate Analog to Digital Converter (ADC) pins. This allows us to factor out any effect changing battery voltage has on our temperature measurement. This code is written for version 2 of the sensor hardware. A pdf of the sensor schematic and board layout is available at datalogger.nublabs.com
Definition at line 90 of file temperature_sensor_Terciopelo.cpp.
References discover(), and initializeSensor().
Referenced by main().
91 {
92   Serial.begin(19200);
93   initializeSensor();
94   discover();
95 }
void waitForSampleInterval ()
this function waits for the time specified by the global variables 'hours,' 'minutes,' and 'seconds' It should ideally put the arduino in a power saving mode
Definition at line 317 of file temperature_sensor_Terciopelo.cpp.
References minutes, seconds, xbeeSleep(), and xbeeWake().
Referenced by loop().
318 {
319   xbeeSleep();
320   delay(60*minutes*1000+seconds*1000);
321   xbeeWake();
322 }
void xbeeSleep ()
Definition at line 377 of file temperature_sensor_Terciopelo.cpp.
References XBEE_SLEEP.
Referenced by waitForSampleInterval().
378 {
379   digitalWrite(XBEE_SLEEP,HIGH);
380 }
void xbeeWake ()
Definition at line 383 of file temperature_sensor_Terciopelo.cpp.
References XBEE_SLEEP.
Referenced by initializeSensor(), and waitForSampleInterval().
384 {
385   digitalWrite(XBEE_SLEEP,LOW);
386 }
Variable Documentation
float B = 3950.0
Definition at line 357 of file temperature_sensor_Terciopelo.cpp.
Referenced by convertToTemperature().
float R0 = 10000.0
Definition at line 356 of file temperature_sensor_Terciopelo.cpp.
Referenced by convertToTemperature().
float RBOTTOM = 1000.0
Definition at line 359 of file temperature_sensor_Terciopelo.cpp.
Referenced by convertToResistance().
float T0 = 298
Definition at line 358 of file temperature_sensor_Terciopelo.cpp.
Referenced by convertToTemperature().