#define OK 0
#define RESEND 1
#define STAND_BY_FOR_CONFIG 2

#define EVERYTHINGS_FINE 22
#define NO_DATA_ERROR 23
#define BAD_CHECKSUM_ERROR 24
#define BAD_PACKET_STRUCTURE_ERROR 25

#define DISCOVER 1
#define DISCOVERY_RESPONSE 2


#define COMM_DELAY 10

//States
#define TURNING_ON 0
#define INITIALIZED 1
#define WAITING_FOR_CONFIG 3
#define CONFIGURED 4
#define SAMPLING 5
#define TURNING_OFF 6
#define BROKEN 7

//Message IDs
#define WHOAMI_IDENTIFIER 10
#define CHECKSUM_IDENTIFIER 11
#define NAME_IDENTIFIER 12
#define CONFIGURATION_IDENTIFIER 13
#define LOGGING_IDENTIFIER 14
#define MESSAGE_START 15
#define MESSAGE_END 16

//Error Messages
#define MALFORMED_MESSAGE 101
#define MISSING_MESSAGE_START 102
#define MISSING_MESSAGE_END 103
#define TIMEOUT 104
