/Users/nikki/nublabs/nub.datalogger/hardware/temperature_sensor_Terciopelo/nublogger.h File Reference
#include <HardwareSerial.h>
#include <string.h>
#include `communications.h`
Functions
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
void discover ()
This function tells the computer of the datalogger's existence.
Function Documentation
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
Definition at line 15 of file nublogger.h.
Referenced by discover().
16 { 
17 }
void discover ()
This function tells the computer of the datalogger's existence.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
Definition at line 27 of file nublogger.h.
References ACKNOWLEDGE, ACKNOWLEDGE_AND_CONFIGURE, configure(), DISCOVER_ME, discovered, getByte(), MESSAGE_END, MESSAGE_START, name, and TRUE.
Referenced by setup().
28 { 
29   unsigned char checksum=0;
30   int i=0;
31   Serial.print(MESSAGE_START, BYTE);
32   Serial.print(DISCOVER_ME,BYTE);
33   Serial.print(name);
34   while(name[i]!=0)
35   {
36     checksum+=name[i];
37     i++;
38   }
39   checksum+=DISCOVER_ME;
40   Serial.print(checksum,BYTE);
41   Serial.print(MESSAGE_END,BYTE);
42 
43   int receivedByte=getByte(100);     //looks for a byte on the serial port with a 100ms timeout
44   if(receivedByte==ACKNOWLEDGE)
45     discovered=TRUE;
46   if(receivedByte==ACKNOWLEDGE_AND_CONFIGURE)
47     {
48       discovered=TRUE;
49       configure();
50     }
51   
52 }