/Users/nikki/nublabs/nub.datalogger/hardware/temperature_sensor_Terciopelo/temperature_sensor_Terciopelo.pde File Reference
#include `name.h`
#include `globals.h`
#include `communications_definitions.h`
#include <stdio.h>
Defines
#define XBEE_SLEEP 2
#define SAMPLE_BUTTON 3
#define LED 4
#define SENSOR1_TOP 0
#define SENSOR1_BOTTOM 1
#define SENSOR2_TOP 2
#define SENSOR2_BOTTOM 3
Functions
void setup ()
void loop ()
void sample ()
int getByte (int timeout)
int getMessage (int timeout)
void sendData ()
this function takes care of putting together a message string, calculating a checksum, sending it out to the computer and making sure the computer got it ok
unsigned char getChecksum ()
this computes a checksum of the global string 'message'
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
void discover ()
This function tells the computer of the datalogger's existence.
void waitForSampleInterval ()
this function waits for the time specified by the global variables 'hours,' 'minutes,' and 'seconds' It should ideally put the arduino in a power saving mode
void initializeSensor ()
this function configures all the digital communication pins as input or output pins
void xbeeSleep ()
void xbeeWake ()
void getTemperatures ()
void getRawData ()
this just grabs the raw values off the analog to digital converter
void convertToResistance ()
this function converts the raw ADC values from the thermistor into resistances of the thermistor
void convertToTemperature ()
Variables
float R0 = 10000.0
float B = 3950.0
float T0 = 298
float RBOTTOM = 1000.0
Define Documentation
#define LED 4
Definition at line 323 of file temperature_sensor_Terciopelo.pde.
#define SAMPLE_BUTTON 3
Definition at line 322 of file temperature_sensor_Terciopelo.pde.
#define SENSOR1_BOTTOM 1
Definition at line 326 of file temperature_sensor_Terciopelo.pde.
#define SENSOR1_TOP 0
Definition at line 325 of file temperature_sensor_Terciopelo.pde.
#define SENSOR2_BOTTOM 3
Definition at line 328 of file temperature_sensor_Terciopelo.pde.
#define SENSOR2_TOP 2
Definition at line 327 of file temperature_sensor_Terciopelo.pde.
#define XBEE_SLEEP 2
these are the pin definitions for the v2 board
function atmega pin arduino pin
Serial RX PD0 0 //serial lines that go out to the xbee module Serial TX PD1 1 Xbee_sleep PD2 2 //a pin that, when asserted, puts the xbee radio into a low power sleep mode Sample_button PD3 3 //an optional button that forces the sensor to take and send out a measurement LED PD4 4 //an LED on board that you can use for all kinds of stuff
sensor1_top PC0 (analog) 0 sensor1_bottom PC1 (analog) 1 sensor2_top PC2 (analog) 2 sensor2_bottom PC3 (analog) 3
Definition at line 321 of file temperature_sensor_Terciopelo.pde.
Function Documentation
void configure ()
configure() runs if the computer is trying to change the sensor's sample rate
In configure(), the datalogger sends a LISTENING message to the computer, indicating that it's ready to receive data. The computer sends three ints: the hours, minutes and seconds of the sample interval, followed by a checksum byte that's the sum of the ints modulo 256. The sensor computes a checksum on the received data. If its checksum matches, it sends an ACKNOWLEDGE message back to the computer and updates its sample interval information. If the checksum does not match, it sends a CHECKSUM_ERROR_PLEASE_RESEND message, asking the computer to send the three ints again, followed by a checksum. If the sensor can't get a valid message (with a matching checksum) after three tries, it gives up, sends a CHECKSUM_ERROR_GIVING_UP message to the computer and keeps its original sample interval information
Definition at line 183 of file temperature_sensor_Terciopelo.pde.
References buffer, CHECKSUM, CHECKSUM_ERROR_GIVING_UP, CHECKSUM_ERROR_PLEASE_RESEND, CONFIGURATION_MESSAGE_LENGTH, configured, getMessage(), HOUR_HIGH, HOUR_LOW, hours, index, LISTENING, MALFORMED_MESSAGE_ERROR_GIVING_UP, MALFORMED_MESSAGE_ERROR_PLEASE_RESEND, MESSAGE_START, MINUTE_HIGH, MINUTE_LOW, minutes, NUM_TRIES, SECOND_HIGH, SECOND_LOW, seconds, start, and TIMEOUT_ERROR.
184 { 
185   char i=0;
186   char tries=0;
187   char success=0;
188   unsigned char checksum=0;
189   int error;
190   
191   while((tries<NUM_TRIES)&&(success==0))     //we'll try
192   {
193   checksum=0;
194   Serial.print(LISTENING,BYTE);
195   error=getMessage(100);
196   if(error==-1)
197     Serial.print(TIMEOUT_ERROR,BYTE);
198   else
199   {
200     if(buffer[start]==MESSAGE_START)
201     {
202       if((index-start)==CONFIGURATION_MESSAGE_LENGTH)    //check to make sure the message is the size we expect
203       {
204         for(i=1;i<CHECKSUM;i++)
205           checksum+=buffer[start+i];
206         if(checksum==buffer[start+CHECKSUM])    //check to see if the calculated checksum is the same as the received checksum
207         {
208           //if it is, then we can load all the sample interval info
209           hours=(int)buffer[start+HOUR_HIGH]*256+(int)buffer[start+HOUR_LOW];
210           minutes=(int)buffer[start+MINUTE_HIGH]*256+(int)buffer[start+MINUTE_LOW];
211           seconds=(int)buffer[start+SECOND_HIGH]*256+(int)buffer[start+SECOND_LOW];
212           success=1;         //we can stop looping
213           configured=1;      //the sensor is configured!
214         }
215         else
216         {
217           if(tries<NUM_TRIES)
218           {
219             Serial.print(CHECKSUM_ERROR_PLEASE_RESEND);
220             tries++;
221           }
222           else
223             Serial.print(CHECKSUM_ERROR_GIVING_UP);
224         }
225       }
226       else      //the message is the wrong size
227         {
228           if(tries<NUM_TRIES)
229           {
230             Serial.print(MALFORMED_MESSAGE_ERROR_PLEASE_RESEND);
231             tries++;
232           }
233           else
234             Serial.print(MALFORMED_MESSAGE_ERROR_GIVING_UP);
235         }
236     }
237     else
238         {
239           if(tries<NUM_TRIES)
240           {
241             Serial.print(MALFORMED_MESSAGE_ERROR_PLEASE_RESEND);
242             tries++;
243           }
244           else
245             Serial.print(MALFORMED_MESSAGE_ERROR_GIVING_UP);
246         }
247   }
248   }
249 }
void convertToResistance ()
this function converts the raw ADC values from the thermistor into resistances of the thermistor
Definition at line 383 of file temperature_sensor_Terciopelo.pde.
References RBOTTOM, sensor1_bottom, sensor1_resistance, and sensor1_top.
Referenced by getTemperatures().
384 {
385     sensor1_resistance = ((float)sensor1_top/(float)sensor1_bottom - 1)*RBOTTOM; // Voltages converted to resistances
386     /* uncomment if I enable two sensing elements
387     sensor2_resistance = ((float)sensor2_top/(float)sensor2_bottom - 1)*RBOTTOM; // Voltages converted to resistances*/
388  
389 }
void convertToTemperature ()
Definition at line 392 of file temperature_sensor_Terciopelo.pde.
References B, R0, sensor1_resistance, sensor1_temperature, and T0.
Referenced by getTemperatures(), and sample().
393 {
394    sensor1_temperature = float(B/log(sensor1_resistance/(R0*exp(-1.0*B/T0))) - 273.0); // Temperature in degrees Celsius
395    /* uncomment if I enable two sensing elements
396    sensor2_temperature = float(B/log(sensor2_resistance/(R0*exp(-1.0*B/T0))) - 273.0); // Temperature in degrees Celsius   */
397 }
void discover ()
This function tells the computer of the datalogger's existence.
When the sensor turns on, it runs discover(). It sends a MESSAGE_START message, a DISCOVER_ME message, and its name out to the computer and waits for acknowledgement. The computer can send back a plain `ACKNOWLEDGE` message, which means that the sensor should run using its default configuration values. The computer can also send back an `ACKNOWLEDGE_AND_CONFIGURE` message, which means that it has configuration data for the sensor. If the sensor gets this message, it'll run configure() to receive the data from the computer.
Definition at line 260 of file temperature_sensor_Terciopelo.pde.
References ACKNOWLEDGE, ACKNOWLEDGE_AND_CONFIGURE, configure(), DISCOVER_ME, discovered, getByte(), MESSAGE_END, MESSAGE_START, name, TIMEOUT_ERROR, and TRUE.
261 { 
262   unsigned char checksum=0;
263   int i=0;
264   Serial.print(MESSAGE_START, BYTE);
265   Serial.print(DISCOVER_ME,BYTE);
266   Serial.print(name);
267   while(name[i]!=0)
268   {
269     checksum+=name[i];
270     i++;
271   }
272   checksum+=DISCOVER_ME;
273   Serial.print(checksum,BYTE);
274   Serial.print(MESSAGE_END,BYTE);
275 
276   int receivedByte=getByte(100);     //looks for a byte on the serial port with a 100ms timeout
277   if(receivedByte==ACKNOWLEDGE)
278     discovered=TRUE;
279   if(receivedByte==ACKNOWLEDGE_AND_CONFIGURE)
280     {
281       discovered=TRUE;
282       configure();
283     }
284   if(receivedByte==-1)
285   {
286     Serial.print(TIMEOUT_ERROR,BYTE);  //getByte didn't get a byte before the timeout
287   }  
288 }
int getByte (int timeout)
Definition at line 94 of file temperature_sensor_Terciopelo.pde.
95 {
96   int currentTime=millis();
97   int maxTime=currentTime+timeout;
98   while((Serial.available()==0)&&(millis()<(maxTime)))
99     {}
100   if(Serial.available()>0)        //did any data come in on the serial port?
101     return Serial.read();
102   else                             //we didn't get any data before the timeout
103     return -1;
104 }
unsigned char getChecksum ()
this computes a checksum of the global string 'message'
Definition at line 159 of file temperature_sensor_Terciopelo.pde.
References message.
Referenced by sendData().
160 {
161   char i=0;
162   unsigned char checksum=0;
163   while(message[i]!=0)
164   {
165     checksum+=message[i];
166     i++;
167   }
168   return checksum;
169 }
int getMessage (int timeout)
Definition at line 106 of file temperature_sensor_Terciopelo.pde.
References buffer, index, MESSAGE_END, and start.
Referenced by configure().
107 {
108   int completeMessage=-1;   //a flag that lets us know if we got a full message
109   start=index;              //drop whatever other data is in our buffer--it'll probably just confuse the functions if we don't
110   int currentTime=millis();
111   int maxTime=currentTime+timeout;  
112   while((millis()<(maxTime))&&(buffer[index]!=MESSAGE_END))
113     {
114       if(Serial.available()>0)
115         {
116           buffer[index]=Serial.read();
117           if(buffer[index]==MESSAGE_END)   //we got a complete message
118             completeMessage=1;
119           index++;
120         }
121     }
122   if(completeMessage==-1)    //we never got a complete message
123     start=index;    //skip past whatever we got from the buffer
124   
125   return completeMessage;
126 }
void getRawData ()
this just grabs the raw values off the analog to digital converter
Definition at line 372 of file temperature_sensor_Terciopelo.pde.
References sensor1_bottom, and sensor1_top.
Referenced by getTemperatures(), and sample().
373 {
374   sensor1_top=analogRead(0);
375   sensor1_bottom=analogRead(1);
376   
377 /*  uncomment if I enable 2-sensing elements per sensor
378   sensor2_top=analogRead(2);
379   sensor2_bottom=analogRead(3);*/
380 }
void getTemperatures ()
Definition at line 364 of file temperature_sensor_Terciopelo.pde.
References convertToResistance(), convertToTemperature(), and getRawData().
365 {
366   getRawData();
367   convertToResistance();
368   convertToTemperature();
369 }
void initializeSensor ()
this function configures all the digital communication pins as input or output pins
If you adapt this code to work with another sensor or board, you should replace the code in initializeSensor() to initialize all your relevant pins
Definition at line 343 of file temperature_sensor_Terciopelo.pde.
References LED, SAMPLE_BUTTON, XBEE_SLEEP, and xbeeWake().
344  {
345    pinMode(XBEE_SLEEP,OUTPUT);
346    pinMode(SAMPLE_BUTTON,INPUT);
347    pinMode(LED,OUTPUT);
348    xbeeWake();
349  }  
void loop ()
Definition at line 79 of file temperature_sensor_Terciopelo.pde.
References sample(), and waitForSampleInterval().
80 {
81   waitForSampleInterval();
82   sample();
83 }
void sample ()
Definition at line 85 of file temperature_sensor_Terciopelo.pde.
References convertToTemperature(), getRawData(), and sendData().
Referenced by loop().
86 {
87   getRawData();
88   convertToTemperature();
89   sendData();
90 }
void sendData ()
this function takes care of putting together a message string, calculating a checksum, sending it out to the computer and making sure the computer got it ok
Definition at line 129 of file temperature_sensor_Terciopelo.pde.
References ACKNOWLEDGE, ACKNOWLEDGE_AND_CONFIGURE, configure(), FALSE, getByte(), getChecksum(), message, MESSAGE_END, MESSAGE_START, NUM_TRIES, sensor1_temperature, and TRUE.
Referenced by sample().
130 {
131   char tries=0;
132   char success=FALSE;
133   int response;
134   while((success==FALSE)&&(tries<NUM_TRIES))
135   {
136     sprintf(message, "thermistor 1 = %f degrees C", sensor1_temperature);
137     unsigned char checksum=getChecksum();
138     Serial.print(MESSAGE_START);
139     Serial.print(message);
140     Serial.print(checksum);
141     Serial.print(MESSAGE_END);
142     response=getByte(50);   //look for the computer's response
143     
144     if(response==ACKNOWLEDGE)   //the computer got the data.  It's happy, we're happy, we're done!
145       success=TRUE;
146     
147     else if(response==ACKNOWLEDGE_AND_CONFIGURE)  //the computer can ask to upload a new configuration at any sample
148     {
149       success=TRUE;
150       configure();
151     }
152     else         //if there was a timeout or a checksum mismatch, then re-try
153       tries++;
154   }
155     
156 }
void setup ()
nublogger temperature sensor Terciopelo(+)
Alex Hornstein 11.19.08 alex@nublabs.com datalogger.nublabs.com
(+)In keeping with the arduino nomenclature, we are naming all our code revisions with Spanish names of venemous snakes. The Terciopelo, or fer-de-lance is a pit viper common in central and northwestern south america. It has a powerful venom that, left untreated, can cause necrosis, brain hemorrhaging, renal failure and death. It's also capable of spraying venom through its fangs for up to 6 feet. Cool, huh? This is a sensor for nublab's datalogging system. The datalogger is a two-part system: There is a USB dongle that plugs into a computer that allows the computer to talk to a wireless Zigbee network, and then there are battery-powered sensors that sense data about the environemnt. The sensors collect data and convert it into human-readable units, and then send the data as plaintext over the wireless network to the computer, where it is stored and logged. Any sensor that will work with this system must implement the discover(), configure() and sample() functions, as well as be identifiable by a unique name
The discover() function is a short communication sequence when the sensor is first turned on where it broadcasts its name over the network and ensures that the computer recognizes it and is ready to configure it and log its data. The sensor also sends the units of whatever value it will be reporting.
the configure() function is triggered by a flag sent by the computer that indicates that the computer would like to change the datalogger's sample rate. configure() is another communication sequence in which the computer sends a sample interval in hours, minutes and seconds to the datalogger. By default, the datalogger samples every second.
the sample() function is called by the sensor every sample interval. sample() reads a value from whatever sensing element (Thermistor, current sensor, light sensor, etc) the particular sensor uses, converts it to physical units (degrees celsius, amps, lux, etc) and sends out a string over the wireless network with the sensor's unique name and its sensed values.
the name: each sensor should have a unique name burnt into its eeprom that makes it uniquely identifiable in the network. Nublabs is using a list of north and south american baby names which is available at datalogger.nublabs.com This particular sensor is a temperature sensor using an NTC thermistor. The thermistor is a resistive element. We sense it using two resistor dividers--one resistor, R1 which connects from Vcc to the thermistor, and another resistor that connects from the other end of the thermistor to ground. We measure the voltage at both ends of the thermistor using separate Analog to Digital Converter (ADC) pins. This allows us to factor out any effect changing battery voltage has on our temperature measurement. This code is written for version 2 of the sensor hardware. A pdf of the sensor schematic and board layout is available at datalogger.nublabs.com
Definition at line 72 of file temperature_sensor_Terciopelo.pde.
References discover(), and initializeSensor().
73 {
74   Serial.begin(19200);
75   initializeSensor();
76   discover();
77 }
void waitForSampleInterval ()
this function waits for the time specified by the global variables 'hours,' 'minutes,' and 'seconds' It should ideally put the arduino in a power saving mode
Definition at line 292 of file temperature_sensor_Terciopelo.pde.
References minutes, seconds, xbeeSleep(), and xbeeWake().
Referenced by loop().
293 {
294   xbeeSleep();
295   delay(60*minutes*1000+seconds*1000);
296   xbeeWake();
297 }
void xbeeSleep ()
Definition at line 352 of file temperature_sensor_Terciopelo.pde.
References XBEE_SLEEP.
Referenced by waitForSampleInterval().
353  {
354    digitalWrite(XBEE_SLEEP,HIGH);
355  }
void xbeeWake ()
Definition at line 358 of file temperature_sensor_Terciopelo.pde.
References XBEE_SLEEP.
Referenced by initializeSensor(), and waitForSampleInterval().
359  {
360    digitalWrite(XBEE_SLEEP,LOW);
361  }
Variable Documentation
float B = 3950.0
Definition at line 332 of file temperature_sensor_Terciopelo.pde.
Referenced by convertToTemperature().
float R0 = 10000.0
Definition at line 331 of file temperature_sensor_Terciopelo.pde.
Referenced by convertToTemperature().
float RBOTTOM = 1000.0
Definition at line 334 of file temperature_sensor_Terciopelo.pde.
Referenced by convertToResistance().
float T0 = 298
Definition at line 333 of file temperature_sensor_Terciopelo.pde.
Referenced by convertToTemperature().